openapi: 3.0.3
info:
  title: Tramways Analysis API
  description: Tramways Analysis API
  version: 1.0.0
servers:
  [ ]
paths:
  { }
components:
  schemas:
    AnalysisResult:
      type: object
      properties:
        uuid:
          type: string
        resultType:
          type: string
      discriminator:
        propertyName: 'resultType'
    XYAnalysisResult:
      allOf:
        - $ref: '#/components/schemas/AnalysisResult'
        - type: object
          properties:
            xLabel:
              type: string
            yLabel:
              type: string
            points:
              type: array
              items:
                $ref: '#/components/schemas/XYPoint'
    XYPoint:
      type: object
      properties:
        x:
          type: number
        y:
          type: number
    StringAnalysisResult:
      allOf:
        - $ref: '#/components/schemas/AnalysisResult'
        - type: object
          properties:
            message:
              type: string
    Property:
      type: object
security:
  - bearerAuth: [ ]

