openapi: 3.0.3
info:
  title: Tramways Analysis API
  description: Tramways Analysis API
  version: 1.0.0
paths:
  { }
components:
  responses:
    Created:
      description: 'Resource created'
      headers:
        Location:
          schema:
            type: string
    Ok:
      description: 'Request successful'
      content:
        application/json:
          schema:
            $ref: 'https://raw.githubusercontent.com/NaigoApps/tramways-commons/master/tramways-commons-rest/src/main/resources/wrappers-api.yaml#/components/schemas/StringWrapper'
    Unauthorized:
      description: 'You are not authorized'
