openapi: 3.0.3
info:
  title: Tramways Analysis API
  description: Tramways Analysis API
  version: 1.0.0
paths:
  {}
components:
  schemas:
    BooleanWrapper:
      $ref: "./BooleanWrapper.yaml"
    StringWrapper:
      $ref: "./StringWrapper.yaml"
    ErrorWrapper:
      $ref: "./ErrorWrapper.yaml"
